### ISSUE TITLE
Reorganize dependencies

### ISSUE THREAD

**Issue by dferber90** [commercetools/eslint-config#10]
### Description

A few general thoughts about dependencies
- `eslint-formatter-pretty` should not be a peer dependency
- `eslint` dependencies should be `peerDependencies`, [see documentation](http://eslint.org/docs/developer-guide/shareable-configs#publishing-a-shareable-config)
- There should be almost no `dependencies` (see how [airbnb](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/package.json) does it)

- `eslint-formatter-pretty` should be updated to 1.0.0

**Comment by emmenko** [comment]
This has been clarified and we're going with that for now.

**Comment by dferber90** [comment]
To clarify, we didn't go with what this issue suggested.


Here's what we did:
- `eslint-formatter-pretty` is a `devDependency` now since its used for testing of this repo only
- all `eslint` related packages are regular dependencies now so the projects using this package
  - don't need to list `eslint` and all related packages as dependencies
  - the versions of the `eslint` packages are fixed, so we can ensure they are compatible (could have done that with `peerDependencies` as well though)
